### ISSUE TITLE
启动的时候报错，是什么原因？

### ISSUE THREAD

**Issue by qianyue725** [asura-pro/pea#10]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.pac4j.play.scala.SecurityComponents was bound.
  while locating org.pac4j.play.scala.SecurityComponents
    for the 4th parameter of pea.app.api.GatlingApi.<init>(GatlingApi.scala:34)
  while locating pea.app.api.GatlingApi
    for the 3rd parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:129):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)

2) No implementation for org.pac4j.play.scala.SecurityComponents was bound.
  while locating org.pac4j.play.scala.SecurityComponents
    for the 4th parameter of pea.app.api.HomeApi.<init>(HomeApi.scala:33)
  while locating pea.app.api.HomeApi
    for the 2nd parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:129):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)

3) No implementation for org.pac4j.play.scala.SecurityComponents was bound.
  while locating org.pac4j.play.scala.SecurityComponents
    for the 4th parameter of pea.app.api.ResourceApi.<init>(ResourceApi.scala:30)
  while locating pea.app.api.ResourceApi
    for the 4th parameter of router.Routes.<init>(Routes.scala:33)
  at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:129):
Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)

3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at com.google.inject.Guice.createInjector(Guice.java:78)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:155)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:56)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:30)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)

**Comment by qianyue725** [comment]
已解决
