### ISSUE TITLE
webEdittorBaseUrl拉不到对应的simulations脚本

### ISSUE THREAD

**Issue by chris-tao** [asura-pro/pea#14]
compiler报错，尝试各种版本的jar包都不行，错误都不太一样，
[debug] p.a.c.ZincCompilerInstance - [sbt]:Full compilation, no sources in previous analysis.
[debug] p.a.c.ZincCompilerInstance - [sbt]:Full compilation, no sources in previous analysis.
[debug] p.a.c.ZincCompilerInstance - [sbt]:All sources are invalidated.
[debug] p.a.c.ZincCompilerInstance - [sbt]:All sources are invalidated.
[debug] p.a.c.ZincCompilerInstance - [sbt]:Initial set of included nodes:
[debug] p.a.c.ZincCompilerInstance - [sbt]:Recompiling all sources: number of invalidated sources > 50.0% of all sources
[info] p.a.c.ZincCompilerInstance - [sbt]:Compiling 12 Scala sources and 2 Java sources to D:\pea\logs\output ...
[debug] p.a.c.ZincCompilerInstance - [sbt]:Initial set of included nodes:
[debug] p.a.c.ZincCompilerInstance - [sbt]:Recompiling all sources: number of invalidated sources > 50.0% of all sources
[info] p.a.c.ZincCompilerInstance - [sbt]:Compiling 12 Scala sources and 2 Java sources to D:\pea\logs\output ...
[debug] p.a.c.ZincCompilerInstance - [sbt]:Returning already retrieved and compiled bridge: D:\Program\sbt\bin\compiler-bridge_2.13-1.3.5.jar.
[debug] p.a.c.ZincCompilerInstance - [sbt]:Returning already retrieved and compiled bridge: D:\Program\sbt\bin\compiler-bridge_2.13-1.3.5.jar.
[error] p.a.c.ZincCompilerInstance - [sbt]:## Exception when compiling 14 sources to D:\pea\logs\output
java.lang.VerifyError: class scala.collection.mutable.LinkedHashMap overrides final method stringPrefix.()Ljava/lang/String;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] p.a.c.ZincCompilerInstance - [sbt]:## Exception when compiling 14 sources to D:\pea\logs\output
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at scala.collection.mutable.LinkedHashMap$.from(LinkedHashMap.scala:30)
        at scala.collection.mutable.LinkedHashMap$.from(LinkedHashMap.scala:24)
        at scala.collection.MapFactory.apply(Factory.scala:390)
        at scala.collection.MapFactory.apply$(Factory.scala:390)
        at scala.tools.nsc.settings.MutableSettings.allSettings$lzycompute(MutableSettings.scala:28)
        at scala.tools.nsc.settings.MutableSettings.allSettings(MutableSettings.scala:28)

**Comment by chris-tao** [comment]
帮忙看下是哪里没有配置好，感谢
