### ISSUE TITLE
Dubbo 的接口声明不能热编译重载

### ISSUE THREAD

**Issue by xcorpio** [asura-pro/pea#6]
https://github.com/asura-pro/pea/blob/master/pea-dubbo/src/main/scala/asura/pea/dubbo/request/CustomReferenceConfig.java#L180  这个地方可以设置使用 `ReloadableClassloader `， 但是实际执行会失效,  如果移除调用 https://github.com/asura-pro/pea/blob/master/app/asura/pea/hook/ApplicationStart.scala#L166  ，就会发现 `ClassNotFound`。

估计会导致, Dubbo 的 Interface 不能重载, 脚本依然可以重载

**Comment by xcorpio** [comment]
java.lang.RuntimeException: [source error] no such class: pea.dubbo.api.GreetingService
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:348)
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:287)
	at org.apache.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:261)
	at org.apache.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:118)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:289)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:250)
	at pea.dubbo.request.ReferenceConfigCache$.get(ReferenceConfigCache.scala:47)
	at pea.dubbo.action.DubboAction.<init>(DubboAction.scala:37)
	at pea.dubbo.action.DubboActionBuilder.build(DubboActionBuilder.scala:24)
	at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
Caused by: javassist.CannotCompileException: [source error] no such class: pea.dubbo.api.GreetingService
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:323)
	at org.apache.dubbo.common.bytecode.ClassGenerator.toClass(ClassGenerator.java:287)
	at org.apache.dubbo.common.bytecode.Wrapper.makeWrapper(Wrapper.java:261)
	at org.apache.dubbo.common.bytecode.Wrapper.getWrapper(Wrapper.java:118)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:289)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:250)
	at pea.dubbo.request.ReferenceConfigCache$.get(ReferenceConfigCache.scala:47)
	at pea.dubbo.action.DubboAction.<init>(DubboAction.scala:37)
Caused by: javassist.compiler.CompileError: no such class: pea.dubbo.api.GreetingService
	at javassist.compiler.MemberResolver.searchImports(MemberResolver.java:468)
	at javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:412)
	at javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:319)
	at javassist.compiler.MemberResolver.resolveJvmClassName(MemberResolver.java:512)
	at javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1158)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:729)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)

**Comment by xcorpio** [comment]
https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/Wrapper.java#L233

`ClassGenerator cc = ClassGenerator.newInstance(cl);`

https://github.com/apache/dubbo/blob/master/dubbo-common/src/main/java/org/apache/dubbo/common/bytecode/ClassGenerator.java#L94

**Comment by xcorpio** [comment]
java.lang.IllegalStateException: pea.dubbo.api.GreetingService
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:234)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244)
	at pea.dubbo.request.ReferenceConfigCache$.get(ReferenceConfigCache.scala:47)
	at pea.dubbo.action.DubboAction.<init>(DubboAction.scala:37)
	at pea.dubbo.action.DubboActionBuilder.build(DubboActionBuilder.scala:24)
	at io.gatling.core.structure.BuildAction.$anonfun$build$1(BuildAction.scala:28)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at io.gatling.core.structure.BuildAction.build(BuildAction.scala:27)
Caused by: java.lang.ClassNotFoundException: pea.dubbo.api.GreetingService
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.dubbo.config.ReferenceConfig.checkAndUpdateSubConfigs(ReferenceConfig.java:231)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:244)
	at pea.dubbo.request.ReferenceConfigCache$.get(ReferenceConfigCache.scala:47)
	at pea.dubbo.action.DubboAction.<init>(DubboAction.scala:37)
